/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Error: typeof import('./components/common/Error/Error.vue')['default']
    FormCheckBox: typeof import('./components/common/FormCheckBox/FormCheckBox.vue')['default']
    FormCheckBoxGroup: typeof import('./components/common/FormCheckBoxGroup/FormCheckBoxGroup.vue')['default']
    FormDate: typeof import('./components/common/FormDate/FormDate.vue')['default']
    FormFile: typeof import('./components/common/FormFile/FormFile.vue')['default']
    FormNumber: typeof import('./components/common/FormNumber/FormNumber.vue')['default']
    FormRadio: typeof import('./components/common/FormRadio/FormRadio.vue')['default']
    FormSelect: typeof import('./components/common/FormSelect/FormSelect.vue')['default']
    FormSwitch: typeof import('./components/common/FormSwitch/FormSwitch.vue')['default']
    FormText: typeof import('./components/common/FormText/FormText.vue')['default']
    FormTextarea: typeof import('./components/common/FormTextArea/FormTextarea.vue')['default']
    FormWrapper: typeof import('./components/common/FormWrapper/FormWrapper.vue')['default']
    Loading: typeof import('./components/common/Loading/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
