export const HTTP_CODE = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
};

export const HTTP_MESSAGE = {
    OK: "Success",
    CREATED: "Created",
    BAD_REQUEST: "Bad Request",
    UNAUTHORIZED: "Unauthorized",
    FORBIDDEN: "Forbidden",
    NOT_FOUND: "Not Found",
    INTERNAL_SERVER_ERROR: "Internal Server Error"
};

export const HTTP_CODE_MESSAGE = {
    [HTTP_CODE.OK]: HTTP_MESSAGE.OK,
    [HTTP_CODE.CREATED]: HTTP_MESSAGE.CREATED,
    [HTTP_CODE.BAD_REQUEST]: HTTP_MESSAGE.BAD_REQUEST,
    [HTTP_CODE.UNAUTHORIZED]: HTTP_MESSAGE.UNAUTHORIZED,
    [HTTP_CODE.FORBIDDEN]: HTTP_MESSAGE.FORBIDDEN,
    [HTTP_CODE.NOT_FOUND]: HTTP_MESSAGE.NOT_FOUND,
    [HTTP_CODE.INTERNAL_SERVER_ERROR]: HTTP_MESSAGE.INTERNAL_SERVER_ERROR
};